config/routes.rb
Rails.application.routes.draw do
  root "stories#index"

  resources :stories, only: [:index, :show] do
    collection do
      get 'refresh'
    end
  end

  get '*path' => 'stories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :story
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index
    @stories = StoriesRepository.new.top_stories
  end

  def show
    @story = Story.find(params[:id])
    @comments = StoriesRepository.new.story_active_comments(params[:id])
  end

  def refresh
    TopStoriesSyncJob.perform_async
    redirect_to root_path
  end

  private

  def record_not_found
    flash[:alert] = "Story not found."
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackerNews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex items-center justify-center flex-col mt-20 mb-10">
      <%= yield %>
    </main>
  </body>
</html>

app/views/stories/index.html.erb
<p><%= flash[:alert] %></p>
<div class="mb-10 font-mono text-center">
  <h2 class="text-lg font-bold">HackerNews Top 10</h2>
  <%= link_to "Refresh ranking", refresh_stories_path, class: "text-xs" %>
</div>
<ul class="justify-center">
  <% @stories.each do |story| %>
    <li class="font-mono hover:cursor-pointer hover:bg-indigo-100 rounded-md px-4 py-4">
      <div class="flex justify-between">
        <h1 class="flex items-center mr-10 text-lg font-bold"><%= story.rank + 1 %></h1>
        <div class="flex flex-row grow">
          <%= link_to story_path(story), class: "grow" do %>
            <div class="text-base">
              <h2><%= story.title %></h2>
            </div>
            <div class="text-sm grid grid-cols-3">
              <span class="text-left"><%= Time.at(story.time).utc %></span>
              <span class="text-center"><%= story.comments.size %> comments</span>
              <span class="text-right">@<%= story.author %></span>
            </div>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/stories/show.html.erb
<h2 class="text-lg font-mono font-bold">
  <%= @story.title %>
</h2>
<div class="flex flex-col max-w-3xl">
  <div class="text-sm grid grid-cols-4 text-center">
    <span><%= Time.at(@story.time).utc %></span>
    <span>@<%= @story.author %></span>
    <span class="mb-5 hover:underline">
      <%= link_to "See link", @story.url %>
    </span>
    <span class="mb-5 hover:underline ">
      <%= link_to "See HN post", "https://news.ycombinator.com/item?id=#{@story.reference_id}" %>
    </span>
  </div>
  <ul class="flex flex-col justify-center">
    <% @comments.each do |comment| %>
      <li class="font-mono mb-5">
        <div class="text-sm	bg-indigo-100 rounded-md px-4 py-4 overflow-auto">
          <%= raw(comment.content) %>
        </div>
        <div class="grid grid-cols-2 text-xs">
          <span><%= Time.at(comment.time).utc %></span>
          <span class="text-right">@<%= comment.author %></span>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<span class="mb-5 hover:underline">
  <%= link_to "Go back", stories_path %>
</span>